### ISSUE TITLE
Использование json

### ISSUE THREAD

**Issue by FrediKats** [Frost-Jack/semester_project_3_team#19]
В readme увидел описание схемы работы с базой, про txt-файл. Кажется, что более удобным способом будет такие json, чтобы не пришлось писать свою логику по превращении в строку.

- [ ] Выбрать либу для работы с json
- [ ] Написать модели, которые будут храниться.
- [ ] Написать логику, которая будет сохранять и доставать данные из json-файлов. Подумать сразу о том, как например сохранить список студентов группы

**Comment by GarnetAki** [comment]
БД эволюционировала из txt в postgres, удобно, надёжно, кайфово
